### ISSUE TITLE
Merge back into iosMath?

### ISSUE THREAD

**Issue by kostub** [AnZhg/MacOSMath#1]
It might be better to create a single repository that has both the Mac and iOS targets as 90%+ of the code will be shared.

see
http://www.knowstack.com/sharing-code-between-ios-and-os-x-apps/

**Comment by AnZhg** [comment]
Yes, that's better. Do you want to do it yourself, or I finish merging and then issue a pull request?

**Comment by AnZhg** [comment]
@kostub Merge back pull request issued.

**Comment by AnZhg** [comment]
@kostub Since Mac version is already merged back, I want to delete this repo. Is this okay?
